services:
  postgres:
      container_name: postgres
      image: postgres:15.1-alpine
      restart: always
      environment:
        POSTGRES_DB: nerdgarten
        POSTGRES_USER: ${POSTGRES_USER}
        POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
        PGDATA: /var/lib/postgresql/data/pgdata
      ports:
        - 5434:5432